# Generated by Django 5.0 on 2023-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
